### ISSUE TITLE
running racketeer on git head: serious problems

### ISSUE THREAD

**Issue by mfelleisen** [miraleung/racketeer#1]
After installing the tool on git head, I opened drracket and switched from #lang racket to BSL. 

-- I noticed that the gc ran a lot, suggesting something's running all the time (even w/o typing) 
-- I started typing and some internal error was raised with the message below: 

change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 92 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517

**Comment by mfelleisen** [comment]
[:~/svn/2HtDP] matthias% change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 1 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517

Some more output from the console where I started: 

% change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 90 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517
change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 92 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517
change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 114 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517
change-style method of text%: expects type <interface:style% instance or style-delta% instance or #f> as 1st argument, given: #<void>; other arguments were: 0 117 #t
  context...:
   /Users/matthias/plt/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:3948:2: core6517

**Comment by miraleung** [comment]
Fixed change-style -- didn't notice it initially due to version conflicts caused by local project relocation. The GC should now run only when there's typing activity.

Thanks for bringing this up, Matthias!
