### ISSUE TITLE
DrRacket doesn't want to quit with racketeer on

### ISSUE THREAD

**Issue by AlexKnauth** [miraleung/racketeer#3]
DrRacket doesn’t seem to want to quit.  I click on the quit option in the menu, it asks me if I really want to quit, I say I do, and then it closes the window, but doesn’t quit the application. I tell it to quit again, nothing happens, and then if I tell my computer to force quit DrRacket, then it comes up with a DrRacket internal error box and then almost immediately after that another little window asking me if I really want to quit, and then a second or so later my computer forces DrRacket to quit and both of those are gone.
This happened three times, and the third time I took a video of it, and with that I managed to read the internal error box:
terminate break
 context:
   /Applications/Racket/April-24/Racket
v6.2.0.2/collects/racket/private/misc.rkt:168:2: channel-put
   /Applications/Racket/April-24/Racket

No more of it is shown in the box in the video I took, and couldn’t scroll down to read the rest of it because my computer forced DrRacket to quit right afterwards.  

If I turn the racketeer tool off it quits normally.

**Comment by AlexKnauth** [comment]
Now it's working fine, but I'm not sure why.

**Comment by AlexKnauth** [comment]
Ok, It quits fine when there's a window open, but if I close the window first and then tell it to quit, then it does what I described before.  But if racketeer isn't loaded, then it quits fine either way.

**Comment by miraleung** [comment]
Did any other activity take place before you tried to quit, like editing code in the new/original window? I haven't been able to reproduce this yet, and for me, DrRacket quits if all windows are closed. Which OS are you on? I'm using v6.1 on Ubuntu.

Thanks for bringing this up. :)

**Comment by AlexKnauth** [comment]
I'm on Mac OS X version 10.9.4, using DrRacket with version 6.2.0.2 from the April 24 2015 snapshot.

Step by step, if I just open DrRacket with racketeer loaded, close the window without doing anything, and then go to the DrRacket menu and click Quit DrRacket, and then when the little window comes up asking "Are you sure you want to quit?" I press Quit, and the little window goes away but it doesn't quit.  

In this state, I can't open a new window, tell it to quit again, or get DrRacket to do anything. So then I tell my computer to force quit DrRacket, and that's when the DrRacket internal error box comes up, almost immediately followed by the "Are you sure you want to quit?" box, and then a second or so later both of those go away when my computer forces DrRacket to quit.

**Comment by miraleung** [comment]
Thanks Alex. I suspect this may have to do with non-terminating threads in Racketeer, but I can't be sure as I don't have a Mac to debug on.

Leaving open for any Mac OS-running Racket devs who may be interested.

**Comment by AlexKnauth** [comment]
This seems to have stopped happening, though I'm not sure why, or if it has really been fixed, but I'm closing this for now.
